### ISSUE TITLE
Can't build?

### ISSUE THREAD

**Issue by timneedham** [quasarframework/quasar-helper-json#2]
Hi,

Really loving Quasar... keen to contribute!
Bit of a newbie though, just tried to build:

`npm run build`

...and hit this:

``` bash

c:\throwaway\quasar-helper-json\node_modules\quasar-framework\dist\umd\quasar.mat.umd.js:19809
      this.$q.screen = this;
                     ^

TypeError: Cannot set property 'screen' of undefined
    at Object.install (c:\throwaway\quasar-helper-json\node_modules\quasar-framework\dist\umd\quasar.mat.umd.js:19809:22)
    at c:\throwaway\quasar-helper-json\node_modules\quasar-framework\dist\umd\quasar.mat.umd.js:854:11
    at Array.forEach (<anonymous>)
    at Object.install (c:\throwaway\quasar-helper-json\node_modules\quasar-framework\dist\umd\quasar.mat.umd.js:851:31)
    at Function.Vue.use (c:\throwaway\quasar-helper-json\node_modules\vue\dist\vue.runtime.common.js:4749:22)
    at c:\throwaway\quasar-helper-json\node_modules\quasar-framework\dist\umd\quasar.mat.umd.js:20098:7
    at c:\throwaway\quasar-helper-json\node_modules\quasar-framework\dist\umd\quasar.mat.umd.js:8:82
    at Object.<anonymous> (c:\throwaway\quasar-helper-json\node_modules\quasar-framework\dist\umd\quasar.mat.umd.js:11:2)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quasar-helper-json@1.0.1 build: `node build/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quasar-helper-json@1.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Am I doing something stupid? `screen` suggests it's a browser thing, have I fundamentally misunderstood this package? 

(also, grabbing this via `npm install quasar-helper-json` doesn't seem to have a `/build` dir, and that's where most of the code lives?)

**Comment by rstoenescu** [comment]
Hi,

This is a bit outdated. Fixed it for upcoming Quasar v0.16.1, but not yet "visible" until the release.
